site_name: DynamoDB Module
site_dir: ../docs
theme: readthedocs
pages:
  - 'Introduction': 'index.md'
  - 'Overview': 'usage.md'
  - 'API': 'api.md'
  - 'Examples': 'example.md'
markdown_extensions:
  - admonition
  - codehilite